# Generated by Django 3.1.5 on 2021-02-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='processo_numero',
            field=models.IntegerField(null=True, unique=True, verbose_name='Numero de processo'),
        ),
    ]
