# Generated by Django 3.1.5 on 2021-02-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitation', '0002_auto_20210207_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='processo_numero',
            field=models.IntegerField(unique=True, verbose_name='Numero de processo'),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='solicitacao_plantao',
            field=models.BooleanField(null=True),
        ),
    ]
