# Generated by Django 3.1.5 on 2021-02-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitation', '0003_auto_20210207_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='processo_status',
            field=models.TextField(null=True),
        ),
    ]
