# Generated by Django 3.1.5 on 2021-02-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitation', '0004_solicitation_processo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='processo_numero',
            field=models.BigIntegerField(unique=True, verbose_name='Numero de processo'),
        ),
    ]
